name: schedule

on:
  schedule:
    # Every 15 minutes between 6am and 11am on weekdays
    - cron: "*/15 5-11 * * 1-5"
    # Every 60 minutes between 12pm and 7pm on weekdays
    - cron: "*/60 12-19 * * 1-5"

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Appointment Check and Notify
        run: |
          curl --request POST \
          --url 'https://citapreviavalencia.com/api/appointments' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
